version: "3"

services:
  python:
    container_name: python_async_chat
    build:
      dockerfile: ${PWD}/server.dockerfile
      context: ${PWD}/app
    command: python server.py && tail -f /dev/null
    working_dir: /app
    volumes:
      - ./app:/app